version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: volk-medusa_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: medusa-store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - volk-medusa_postgres_data:/var/lib/postgresql/data
    networks:
      - volk-medusa_network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: volk-medusa_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - volk-medusa_network

  # Medusa Server
  medusa:
    build: .
    container_name: volk-medusa_backend
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/medusa-store
      - REDIS_URL=redis://redis:6379
      - MEDUSA_BACKEND_URL=http://localhost:9000
    networks:
      - volk-medusa_network

volumes:
  volk-medusa_postgres_data:

networks:
  volk-medusa_network:
    driver: bridge
